credentials:
  usernames:
    kkuseyri:
      email: kerem.kuseyri@geneltransport.com.tr
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Kerem Kuseyri
      password: '123456' # Will be hashed automatically
    kcebeci:
      email: kubilay.cebeci@geneltransport.com.tr
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Kubilay Cebeci
      password: '123456' # Will be hashed automatically
cookie:
  expiry_days: 1
  key: abcdef # Must be string
  name: session_cookie
pre-authorized:
  emails: