cookie:
  expiry_days: 1
  key: abc
  name: session_cookie
credentials:
  usernames:
    osakar:
      email: ozkan.sakar@geneltransport.com.tr
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Özkan Sakar
      password: 'sATLDn7K' # Will be hashed automatically
    kkuseyri:
      email: kerem.kuseyri@geneltransport.com.tr
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Kerem Kuseyri
      password: '123456' # Will be hashed automatically
    kcebeci:
      email: kubilay.cebeci@geneltransport.com.tr
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Kubilay Cebeci
      password: '123456' # Will be hashed automatically
    terkeskin:
      email: turgut.erkeskin@geneltransport.com.tr
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Turgut Erkeskin
      password: 'QhcKjLAz' # Will be hashed automatically
    uaydemir:
      email: uveysaydemir@geneltransport.com.tr
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Üveys Aydemir
      password: '123456' # Will be hashed automatically
    bayhan:
      email: baranayhan@geneltransport.com.tr
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Baran Ayhan
      password: 'NGWhm5Ew'
    scelik:
      email: senemcelik@geneltransport.com.tr
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Senem Çelik
      password: 'TuwZJdjx'
    air :
      email: air@geneltransport.com.tr
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Air Report
      password: 'gt1303'      
    sea :
      email: sea@geneltransport.com.tr
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Sea Report
      password: 'gt1303'       
    road :
      email: road@geneltransport.com.tr
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Road Report
      password: 'gt1303' 
    aerospace :
      email: aero@geneltransport.com.tr
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Aerospace Report
      password: 'gt1303' 
    project :
      email: project@geneltransport.com.tr
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Project Report
      password: 'gt1303' 
pre-authorized:
  emails: 
